# Generated by Django 2.0.6 on 2018-06-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(default='admin', max_length=100)),
                ('Passwd', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
